## Python Basic

In [1]:
a = 3
b = 2
a + b

5

In [2]:
a * 10

30

In [3]:
a + 5

8

## 英文斷詞 

In [4]:
s = 'this is a  book'

In [5]:
type(s)

str

In [6]:
print(dir(s))

['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']


In [7]:
help(s.split)

Help on built-in function split:

split(...) method of builtins.str instance
    S.split(sep=None, maxsplit=-1) -> list of strings
    
    Return a list of the words in S, using sep as the
    delimiter string.  If maxsplit is given, at most maxsplit
    splits are done. If sep is not specified or is None, any
    whitespace string is a separator and empty strings are
    removed from the result.



In [8]:
s.split()

['this', 'is', 'a', 'book']

In [9]:
a = '''
今天除了清晨中南部沿海有短暫降雨外，仍是午後雷陣雨為主的天氣型態。氣象預報員陳建安表示，因為太平洋高壓減弱，上半天各地大多為多雲，午後各地山區與近山區都要留意局部大雨跟豪雨的發生機率。加上今天風場偏西南風、水汽較多，北部、東北部地區午後雷陣雨範圍較廣，可能會影響至平地地區，提醒民眾記得攜帶雨具。
'''

In [11]:
import re
re.split('，|。|、', a)

['\n今天除了清晨中南部沿海有短暫降雨外',
 '仍是午後雷陣雨為主的天氣型態',
 '氣象預報員陳建安表示',
 '因為太平洋高壓減弱',
 '上半天各地大多為多雲',
 '午後各地山區與近山區都要留意局部大雨跟豪雨的發生機率',
 '加上今天風場偏西南風',
 '水汽較多',
 '北部',
 '東北部地區午後雷陣雨範圍較廣',
 '可能會影響至平地地區',
 '提醒民眾記得攜帶雨具',
 '\n']

## 使用Jieba

In [16]:
! pip install /Users/davidchiu/Desktop/jieba-master.zip

Processing /Users/davidchiu/Desktop/jieba-master.zip
  Running setup.py bdist_wheel for jieba ... done
  Stored in directory: /Users/davidchiu/Library/Caches/pip/wheels/be/21/28/e0bfffcff93e8c8ed12617d1c0e9db29edfe47e8b43e6f17c5
Successfully built jieba
You are using pip version 9.0.1, however version 19.2.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [12]:
import jieba

In [13]:
jieba.cut('大巨蛋案對市府同仁下封口令？　柯P否認')

<generator object Tokenizer.cut at 0x103c91f68>

In [22]:
seg = jieba.cut('大巨蛋案對市府同仁下封口令？　柯P否認')
for w in seg:
    print(w)

大巨蛋案
對
市府
同仁
下
封口
令
？
　
柯P
否認


In [23]:
help(jieba.cut)

Help on method cut in module jieba:

cut(sentence, cut_all=False, HMM=True) method of jieba.Tokenizer instance
    The main function that segments an entire sentence that contains
    Chinese characters into seperated words.
    
    Parameter:
        - sentence: The str(unicode) to be segmented.
        - cut_all: Model type. True for full pattern, False for accurate pattern.
        - HMM: Whether to use the Hidden Markov Model.



In [24]:
?jieba.cut

In [25]:
import jieba

seg_list = jieba.cut("大巨蛋案對市府同仁下封口令？　柯P否認", cut_all=True)
print("Full Mode:", "/ ".join(seg_list))

Full Mode: 大巨蛋/ 大巨蛋案/ 巨蛋/ 巨蛋案/ 蛋案/ 對/ 市府/ 同仁/ 下/ 封口/ 口令/ / / / 柯/ P/ 否認


In [27]:
seg_list = jieba.cut("大巨蛋案對市府同仁下封口令？　柯P否認", cut_all=False, HMM=False)
print("Default Mode:", "/ ".join(seg_list))

Default Mode: 大巨蛋案/ 對/ 市府/ 同仁/ 下/ 封口/ 令/ ？/ 　/ 柯P/ 否認


In [28]:
import jieba
s = '我覺得這個idea非常的great'
list(jieba.cut(s))

['我', '覺得', '這', '個', 'idea', '非常', '的', 'great']

In [1]:
import jieba
jieba.load_userdict('userdict.txt')
seg_list = jieba.cut("大巨蛋案對市府同仁下封口令？　柯P否認", cut_all=False)
print("Default Mode:", "/ ".join(seg_list))

Building prefix dict from the default dictionary ...
Loading model from cache /var/folders/46/b7dzk4mn6g54qzptv608w7d00000gn/T/jieba.cache
Loading model cost 0.691 seconds.
Prefix dict has been built succesfully.


Default Mode: 大巨蛋案/ 對/ 市府/ 同仁/ 下/ 封口令/ ？/ 　/ 柯P/ 否認


In [4]:
import jieba.posseg as pseg
jieba.load_userdict('userdict.txt')
words = pseg.cut("大巨蛋案對市府同仁下封口令？　柯P否認")
for w in words:
    print(w.word, w.flag)


大巨蛋案 N
對 P
市府 N
同仁 N
下 POST
封口令 n
？ x
　 x
柯P N
否認 Vt


In [3]:
#jieba.add_word('封口令')
import jieba
jieba.load_userdict('userdict.txt')
seg_list = jieba.cut("大巨蛋案對市府同仁下封口令？　柯P否認", cut_all=False)
print("Default Mode:", "/ ".join(seg_list))

Default Mode: 大巨蛋案/ 對/ 市府/ 同仁/ 下/ 封口令/ ？/ 　/ 柯P/ 否認


In [4]:
sentence = "大巨蛋案對市府同仁下封口令？　柯P否認"
words = jieba.tokenize(sentence)

for tw in words:
    print(tw[0], tw[1], tw[2])


大巨蛋案 0 4
對 4 5
市府 5 7
同仁 7 9
下 9 10
封口令 10 13
？ 13 14
　 14 15
柯P 15 17
否認 17 19


In [3]:
import jieba
#sentence = '仍是午後雷陣雨為主的天氣型態'
#sentence = '私菸案記者會模糊焦點 律師點出華航避談這個重大關鍵'
jieba.load_userdict('userdict.txt')
sentence = "大巨蛋案對市府同仁下封口令？　柯P否認"
for w in jieba.cut(sentence):
    print(w)

大巨蛋案
對
市府
同仁
下
封口令
？
　
柯P
否認


## 使用內部資料建立辭典

In [4]:
s = '那酸民婉君也可報名嗎?'
s[0:2]

'那酸'

In [5]:
s[1:3]

'酸民'

In [7]:
for i in range(0, len(s) - 2  + 1):
    print(s[i:i+2])

那酸
酸民
民婉
婉君
君也
也可
可報
報名
名嗎
嗎?


In [8]:
for i in range(0, len(s) - 3  + 1):
    print(s[i:i+3])

那酸民
酸民婉
民婉君
婉君也
君也可
也可報
可報名
報名嗎
名嗎?


In [16]:
def ngram(input_sentence, n = 2):
    ary = []
    for i in range(0, len(input_sentence) - n  + 1):
        ary.append(input_sentence[i:i+n])
    return ary

In [17]:
ngram(s, n = 2)

['那酸', '酸民', '民婉', '婉君', '君也', '也可', '可報', '報名', '名嗎', '嗎?']

In [18]:
ngram(s, n = 3)

['那酸民', '酸民婉', '民婉君', '婉君也', '君也可', '也可報', '可報名', '報名嗎', '名嗎?']

In [19]:
news = '''
國安局人員走私菸品案持續延燒，華航昨天開記者會說明，董事長謝世謙鞠躬致歉，但說法卻漏洞百出、避重就輕。律師指出，華航避談核心問題，「何人指示配合機邊交貨、放保稅倉庫」，此人恐有幫助逃漏關稅、走私的責任。

謝世謙昨天強調，這次所有交易都在空中飛機上完成，屬於境外交易，所謂「刷卡五筆、幾百萬」並非在國內完成。但有法界人士指出，謝世謙認為菸品案均在機上刷卡，屬於境外交易，但此說法誤導社會大眾，華航屬於國籍航空，尤其空軍一號更是總統專機，即使在機上刷卡，也是屬於我國領土，加上特勤人員在國內預購，交貨犯罪地點也位於桃園機場，如何能算境外？

律師翁偉倫指出，若撇除華航是公股航空公司，無論國內、國外或是機上刷卡，客戶要花錢訂購多大量的商品，都是客戶的權利，公司出貨也不會有問題；而華航屬於公股公司，也早有相關規定一人購買菸品的數量，而專機未依菸害防制辦法放寬菸品數量限制，確實有行政疏失，內控有問題需要改善，但此部分均非本案重點。

他說，華航昨日記者會內容避重就輕、模糊焦點，如今華航最大的問題是配合機邊交貨，但華航卻避談「是誰指示、核准配合機邊交貨、混入總統專機行李、菸品放入保稅倉庫？」此部分才是牽涉到刑法構成要件，下令指示者有幫助逃漏關稅、幫助走私的責任。
'''

### Python Collections
- https://docs.python.org/zh-tw/3/library/collections.html

In [22]:
a = [1,2,2,1,2,2,3,4,2]
from collections import Counter
c = Counter(a)
c

Counter({1: 2, 2: 5, 3: 1, 4: 1})

In [23]:
c.most_common(3)

[(2, 5), (1, 2), (3, 1)]

In [24]:
words = ngram(news, n = 2)
from collections import Counter
c = Counter(words)
c.most_common(10)

[('華航', 8),
 ('菸品', 5),
 ('屬於', 5),
 ('，華', 4),
 ('，但', 4),
 ('問題', 4),
 ('交貨', 4),
 ('機上', 4),
 ('刷卡', 4),
 ('走私', 3)]

In [25]:
words = ngram(news, n = 3)
from collections import Counter
c = Counter(words)
c.most_common(10)

[('，華航', 4),
 ('謝世謙', 3),
 ('指出，', 3),
 ('配合機', 3),
 ('合機邊', 3),
 ('機邊交', 3),
 ('邊交貨', 3),
 ('機上刷', 3),
 ('上刷卡', 3),
 ('刷卡，', 3)]

In [26]:
words = ngram(news, n = 4)
from collections import Counter
c = Counter(words)
c.most_common(10)

[('配合機邊', 3),
 ('合機邊交', 3),
 ('機邊交貨', 3),
 ('機上刷卡', 3),
 ('上刷卡，', 3),
 ('，華航昨', 2),
 ('避重就輕', 2),
 ('邊交貨、', 2),
 ('保稅倉庫', 2),
 ('有幫助逃', 2)]

In [33]:
import re
sentence_ary = re.split('、|，|「|」|？|。|\n', news)

In [35]:
a = '比特幣期貨，美核准上市'
a.replace('比特幣', '').replace('期貨', '')

'，美核准上市'

In [38]:
def removeKey(text, keywords):
    ret = text
    for word in keywords:
        ret = ret.replace(word, '')
    return ret

In [39]:
removeKey(a, ['比特幣','核准'])

'期貨，美上市'

In [41]:
import re
sentence_ary = re.split('、|，|「|」|？|。|\n', news)

In [47]:
keywords = ['國安局']
words = []
for sentence in sentence_ary:
    text = removeKey(sentence, keywords)
    words.extend(ngram(text, n=4))
#print(words)
c = Counter(words)
c.most_common(3)

[('配合機邊', 3), ('合機邊交', 3), ('機邊交貨', 3)]

In [50]:
keywords = []
for n in range(4, 1, -1):
    words = []
    for sentence in sentence_ary:
        text = removeKey(sentence, keywords)
        words.extend(ngram(text, n = n))
    c = Counter(words)
    for k,v in c.items():
        if v >=3:
            keywords.append(k)
keywords

['配合機邊',
 '合機邊交',
 '機邊交貨',
 '機上刷卡',
 '謝世謙',
 '走私',
 '菸品',
 '華航',
 '指出',
 '問題',
 '指示',
 '交貨',
 '幫助',
 '交易',
 '屬於',
 '境外',
 '國內',
 '專機',
 '公司']

In [54]:
def getLongTermFirst(news):
    sentence_ary = re.split('、|，|「|」|？|。|\n', news)
    keywords = []
    for n in range(5, 1, -1):
        words = []
        for sentence in sentence_ary:
            text = removeKey(sentence, keywords)
            words.extend(ngram(text, n = n))
        c = Counter(words)
        for k,v in c.items():
            if v >=3:
                keywords.append(k)
    return keywords

In [55]:
news = '''迎戰2020大選，國民黨文傳系統整軍待發，但卻遭爆發言人系統大換將，前主席洪秀柱時代任黨發言人至今的台北市議員王鴻薇與副主委洪孟楷都遭拔發言人職務，周二縣市黨部主委會報介紹發言人已確定不見兩人名字。

對此，洪孟楷表示，並不知道是否已遭除名。王鴻薇也說，並未被告知已非黨發言人，但自己原就想請辭，黨有需要再幫忙就好，就像她將與另一黨發言人歐陽龍主持728全代會開閉幕造勢活動，被請辭發言人「沒有關係」。

距2020總統與立委選舉剩不到半年，國民黨文宣攻防系統加緊腳步整理砲管，除參考2007與2011總統大選勝選模式，自7月1日起將黨政策會、黨團與智庫架起的三方平台升級為2020選戰PK小組，每周一會決定當周攻防議題，提升攻防火力。

文傳會也協助分析每日輿情，找出當日文宣打點與社群媒體發文主題，並組政論節目名嘴群組，提供黨政策論述或大選文宣資料，以利協助議題攻防；還研擬選戰議題說帖，供各縣市黨部、黨籍立委參選人攻防使用，統一選戰口徑，加強火力。

此外，文傳會還將成立「新媒體文宣執行策略小組」，協助立委參選人蒐集在地輿情，並進行網路大數據分析，配合中央主要選戰策略，提供相關資料給縣市黨部文宣組與立委參選人使用，力拚國會席次過半。

只不過國民黨積極備戰，黨內卻屢傳發言人系統重整、陣前換將。文傳會周二在縣市黨部主委會報中所提供資料也證實，今天2月27日成立的新版「發言人制度」後，近日確實已將任發言人約3年的王鴻薇、洪孟楷除名。

目前發言系統僅有1月底到任的首席發言人歐陽龍，2月底出任副發言人的智庫副召集人黃心華與青年黨工洪于茜3人，戰力略顯薄弱。也因此，黨務人士還在周二會議上公開呼籲與會者推薦青年副發言人人選。'''

In [56]:
getLongTermFirst(news)

['立委參選人',
 '2020',
 '黨發言人',
 '縣市黨部',
 '國民黨',
 '發言人',
 '王鴻薇',
 '洪孟楷',
 '文傳會',
 '大選',
 '系統',
 '主委',
 '周二',
 '文宣',
 '攻防',
 '選戰',
 '議題',
 '協助',
 '提供',
 '資料']

In [57]:
words = getLongTermFirst(news)
with open('userdict.txt', 'a', encoding='utf-8') as f:
    f.write('\n')
    for w in words:
        f.write(w+'\n')

## 文字量化分析

### Method 1

In [62]:
a = [1,1,2,2,1,2,3,3,2]
dic = {}
for e in a:
    if e not in dic:
        dic[e] = 1
    else:
        dic[e] = dic[e] + 1
dic

{1: 3, 2: 4, 3: 2}

In [63]:
dic.items()

dict_items([(1, 3), (2, 4), (3, 2)])

In [64]:
sorted(dic.items(), key=lambda e: e[1])

[(3, 2), (1, 3), (2, 4)]

In [65]:
sorted(dic.items(), key=lambda e: e[1], reverse=True)

[(2, 4), (1, 3), (3, 2)]

In [66]:
import jieba
jieba.load_userdict('userdict.txt')
dic = {}
for w in jieba.cut(news):
    if w not in dic:
        dic[w] = 1
    else:
        dic[w] = dic[w] + 1
#dic

In [68]:
swd = sorted(dic.items(), key=lambda e: e[1], reverse=True)
swd[0:10]

[('，', 35),
 ('\n', 12),
 ('發言人', 10),
 ('。', 10),
 ('與', 7),
 ('將', 6),
 ('的', 6),
 ('系統', 5),
 ('攻防', 5),
 ('縣市黨部', 4)]

In [69]:
a = ('發言人', 10)
k,v = a
k

'發言人'

In [71]:
for k,v in swd[0:30]:
    if len(k) >= 2:
        print(k,v)

發言人 10
系統 5
攻防 5
縣市黨部 4
文宣 4
選戰 4
2020 3
大選 3
國民黨 3
黨發言人 3
王鴻薇 3
洪孟楷 3
周二 3
議題 3


### Method 2

In [76]:
import jieba
from collections import Counter
jieba.load_userdict('userdict.txt')
c = Counter(list(jieba.cut(news)))
for k,v in c.most_common(30):
    if len(k) >= 2:
        print(k,v)

發言人 10
系統 5
攻防 5
縣市黨部 4
文宣 4
選戰 4
2020 3
大選 3
國民黨 3
黨發言人 3
王鴻薇 3
洪孟楷 3
周二 3
議題 3


In [78]:
import jieba
import re
from collections import Counter
jieba.load_userdict('userdict.txt')
c = Counter(list(jieba.cut(news)))
for k,v in c.most_common(30):
    if len(k) >= 2 and re.match('^[\u4e00-\u9fa5]+$', k):
        print(k,v)

發言人 10
系統 5
攻防 5
縣市黨部 4
文宣 4
選戰 4
大選 3
國民黨 3
黨發言人 3
王鴻薇 3
洪孟楷 3
周二 3
議題 3


In [79]:
news = '''
法國將開始徵收數位服務稅（Digital Service Tax），但我國財政部表示，考量到稅制不同，以及已在現行稅制下針對境外電商課稅等兩項理由，台灣不會跟進課數位服務稅。

財政部表示，台灣透過簡化課稅方式，對於數位服務的課稅可說是「領先全球」，且不論營業稅、營利事業所得稅都能課到。

資誠稅務諮詢顧問公司表示，雖然法國「數位服務稅」對台商直接影響有限，但若是屬網際網路、數位服務等產業，並以海外使用者為重要收入來源者，應密切關注相關法令變動。

法國參議院11日通過新法令，成為歐盟第一個徵收「數位服務稅」國家，並追溯至今年1月1日適用，蘋果、臉書等跨國集團首當其衝。

經濟日報提供
經濟日報提供
但財政部官員表示，首先，歐洲國家稅制與台灣不同，法國等國家判斷課稅權的依據，是根據該公司在境內是否有「固定營業場所」；而台灣課稅權判定則是根據是否有我國來源所得。
由於多數提供數位服務的跨國公司，通常不會在當地設有常設機構，對法國等國家而言，就形成租稅漏洞，因此必須透過課徵數位服務稅，藉此來「補破網」。

財政部官員解讀，對這些歐洲國家而言應只是暫時性解決方案，事實上，經濟合作發展組織（OECD）已在整合數位稅方案，預計今年10月向G20提出版本，屆時才會有課稅方案。

但台灣稅制採「來源法則」，公司如果有我國來源所得就要課稅，對於像是線上訂房網、叫車平台等提供數位服務的境外電商，財政部在現行稅制已有一套課稅方法，該課的稅都課得到。

依財政部規定，在中華民國境內無固定營業場所但銷售電子勞務給境內自然人的境外電商，年銷售額只要逾新台幣48萬元者，就須辦理稅籍登記，報繳營業稅。

而有了稅籍登記作為基礎，國稅局可推算境外電商在台灣的銷售狀況，境外電商可採核實計算所得額並繳稅外，也可申請按營業項目適用同業利潤標準淨利率計算所得，再根據「利潤貢獻度」，計算應稅所得。
'''

In [80]:
words = getLongTermFirst(news)
with open('userdict.txt', 'a', encoding='utf-8') as f:
    f.write('\n')
    for w in words:
        f.write(w+'\n')

In [83]:
import jieba
import re
from collections import Counter
jieba.load_userdict('userdict.txt')
c = Counter(list(jieba.cut(news)))
for k,v in c.most_common(30):
    if len(k) >= 2 and re.match('^[\u4e00-\u9fa5]+$', k):
        print(k,v)

財政部 6
課稅 6
台灣 6
法國 5
數位服務稅 5
稅制 5
境外電商 5
國家 5
表示 4
公司 4
來源 4
提供 4
所得 4
我國 3
數位服務的 3


## TFIDF

In [85]:
import math

In [84]:
a, abb, abc = ['a'], ['a', 'b', 'b'], ['a', 'b', 'c']
D = [a, abb, abc]

In [86]:
#tfidf('a', a, D)
tf = 1 / 1
idf = math.log(3/3)
tf * idf

0.0

In [87]:
#tfidf('a', abb, D)
tf = 1 / 3
idf = math.log(3/3)
tf * idf

0.0

In [88]:
#tfidf('a', abc, D)
tf = 1 / 3
idf = math.log(3/3)
tf * idf

0.0

In [89]:
#tfidf('b', abb, D)
tf = 2 / 3
idf = math.log(3/2)
tf * idf

0.27031007207210955

In [90]:
#tfidf('b', abc, D)
tf = 1 / 3
idf = math.log(3/2)
tf * idf

0.13515503603605478

In [91]:
#tfidf('c', abc, D)
tf = 1 / 3
idf = math.log(3/1)
tf * idf

0.3662040962227032

In [95]:
ary = []
for doc in D:
    if 'c' in doc:
        ary.append(doc)
len(ary)

1

In [96]:
def tfidf(t, d, D):
    tf = d.count(t) / len(d)
    idf = math.log(len(D) / len([doc for doc in D if t in doc]))
    return tf * idf

In [97]:
tfidf('a', a, D)

0.0

In [98]:
tfidf('a', abb, D)

0.0

In [99]:
tfidf('a', abc, D)

0.0

In [100]:
tfidf('b', abb, D)

0.27031007207210955

In [101]:
tfidf('b', abc, D)

0.13515503603605478

In [102]:
tfidf('c', abc, D)

0.3662040962227032

In [104]:
import jieba.analyse
tags = jieba.analyse.extract_tags(news, 10)
tags

['財政部', '課稅', '台灣', '法國', '數位服務稅', '稅制', '境外電商', '國家', '來源', '我國']

## 詞頻矩陣

In [105]:
a = '柯文哲為了大巨蛋一事，找趙藤雄算帳'
b = '柯文哲為了大巨蛋無法舉辦世運會，與趙藤雄對簿公堂'
a == b

False

In [108]:
content = ['How to format my hard disk', 'Hard disk format problems']

['how', 'to', 'format', 'my', 'hard', 'disk']

In [112]:
words = set(content[0].lower().split()) | set(content[1].lower().split())
words

{'disk', 'format', 'hard', 'how', 'my', 'problems', 'to'}

In [114]:
id_to_word = {}
word_to_id = {}
for idx, w in enumerate(words):
    id_to_word[idx]  = w
    word_to_id[w] = idx

In [115]:
id_to_word

{0: 'hard', 1: 'disk', 2: 'how', 3: 'format', 4: 'problems', 5: 'my', 6: 'to'}

In [116]:
word_to_id

{'hard': 0, 'disk': 1, 'how': 2, 'format': 3, 'problems': 4, 'my': 5, 'to': 6}

In [121]:
import numpy as np
m = np.zeros((7,2))

In [124]:

for w in content[0].lower().split():
    m[word_to_id[w], 0] = 1

In [125]:
m

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.]])

In [126]:

for w in content[1].lower().split():
    m[word_to_id[w], 1] = 1

In [127]:
m

array([[1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.]])

In [131]:
((m[:,0] - m[:,1] ) ** 2).sum()

4.0

In [132]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(content)

In [135]:
print(vectorizer.get_feature_names())

['disk', 'format', 'hard', 'how', 'my', 'problems', 'to']


In [134]:
X.toarray()

array([[1, 1, 1, 1, 1, 0, 1],
       [1, 1, 1, 0, 0, 1, 0]], dtype=int64)

In [137]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(content)

In [139]:
X.toarray()

array([[0.33471228, 0.33471228, 0.33471228, 0.47042643, 0.47042643,
        0.        , 0.47042643],
       [0.44832087, 0.44832087, 0.44832087, 0.        , 0.        ,
        0.63009934, 0.        ]])